name: CI/CD Deployment
 
# Trigger: This workflow will run when code is pushed to the 'main' branch
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      # Step 1: Checkout Code from Repository
      - name: Checkout Code
        uses: actions/checkout@v3
 
      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
 
      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ashutoshqsofte/asikhfarm:latest .
 
      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push ashutoshqsofte/asikhfarm:latest
 
      # Step 5: Deploy to Remote Server
      - name: Deploy to Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<EOF
          docker pull ashutoshqsofte/asikhfarm:latest
          docker stop asikhfarm || true
          docker rm asikhfarm || true
          docker run -d --name asikhfarm -p 5000:5000 ashutoshqsofte/asikhfarm:latest
          EOF
